[tool.pytest.ini_options]
addopts = [
    '--cov=src',
    '--cov-report=xml',
    '--cov-report=term',
    '-vv',
    '--workers=auto',
]
pythonpath = [
    '.',
    'src/language',
    
]
testpaths = ['tests']