[tool.pytest.ini_options]
addopts = [
    '--cov=src',
    '--cov-report=xml',
    '--cov-report=term',
    '-vv',
    '-n=6',
    '-s',
    '--dist=loadgroup',
]
pythonpath = [
    '.',
    'src/language',
    
]
testpaths = ['tests']