# src/agents/research/config/tasks.yml
research:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find the latest and most interesting and relevant information. Identify key trends, breakthrough technologies, and potential industry impacts.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

write:
  description: >
    Review the context you got, develop an engaging summary blog post that highlights the most significant advancements in {topic}.
    Make sure the report is detailed and contains relevant and correct information. Your post should be informative, concise and yet accessible.
  expected_output: >
    A summary of all the mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: writer

critique:
  description: >
    Critic the writer's blog post, about {topic}, ensure it stays on topic and is informative, detailed and yet the summary is concise.
  expected_output: >
    A critique that helps the writer improve content.
  agent: critic

